Handle exception on subscription initialization (#1940)
### :pencil: Description

In case of Subscription initiation failure, for example exception thrown
after some custom authentication/authorisation mechanism throws
exception, error was not passed through as response body, because of
exception:
```
java.lang.NullPointerException: graphQL.execute(input)
    …<Flow<ExecutionResult>>() must not be null
   at com.expediagroup.graphql.server.execution.GraphQLRequestHandler.executeSubscription(GraphQLRequestHandler.kt:167)
 ```

### :link: Related Issues
-